name: base
channels:
  - conda-forge
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - archspec=0.2.5=pyhd8ed1ab_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - boltons=25.0.0=pyhd8ed1ab_0
  - brotli-python=1.2.0=py312hc6d9e41_1
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.11.12=h4c7d964_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py312he06e257_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - conda=25.11.0=py312h2e8e312_0
  - conda-libmamba-solver=25.11.0=pyhd8ed1ab_0
  - conda-package-handling=2.4.0=pyh7900ff3_2
  - conda-package-streaming=0.12.0=pyhd8ed1ab_0
  - cpp-expected=1.3.1=h477610d_0
  - cpython=3.12.12=py312hd8ed1ab_2
  - debugpy=1.8.20=py312ha1a9051_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - distro=1.9.0=pyhd8ed1ab_1
  - executing=2.2.1=pyhd8ed1ab_0
  - fmt=12.0.0=h29169d4_0
  - frozendict=2.4.7=py312he06e257_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.10.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jsonpatch=1.33=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py312h2e8e312_2
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - krb5=1.21.3=hdf4eb48_0
  - libarchive=3.8.2=gpl_h26aea39_100
  - libcurl=8.17.0=h43ecb02_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libiconv=1.18=hc1393d2_2
  - liblzma=5.8.1=h2466b09_2
  - libmamba=2.4.0=h3f46830_1
  - libmambapy=2.4.0=py312h6891394_1
  - libsodium=1.0.20=hc70643c_0
  - libsolv=0.7.35=h8883371_0
  - libsqlite=3.51.1=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libxml2=2.15.1=h5d26750_0
  - libxml2-16=2.15.1=h692994f_0
  - libzlib=1.3.1=h2466b09_2
  - lz4-c=1.10.0=h2466b09_1
  - lzo=2.10=h6a83c73_1002
  - mamba=2.4.0=h794742e_1
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - menuinst=2.4.1=py312hbb81ca0_0
  - miniforge_console_shortcut=1.0=h57928b3_0
  - msgpack-python=1.1.2=py312hf90b1b7_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nlohmann_json-abi=3.12.0=h0f90c79_1
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pip=25.3=pyh8b19718_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - pluggy=1.6.0=pyhf9edf01_1
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.2=py312he5662c2_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybind11-abi=11=hc364b38_1
  - pycosat=0.6.6=py312he06e257_3
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.12.12=h0159041_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.12.12=hd8ed1ab_2
  - python_abi=3.12=8_cp312
  - pywin32=311=py312h829343e_1
  - pyzmq=27.1.0=py312hbb5da91_0
  - reproc=14.2.5.post0=h2466b09_0
  - reproc-cpp=14.2.5.post0=he0c23c2_0
  - requests=2.32.5=pyhd8ed1ab_0
  - ruamel.yaml=0.18.16=py312he06e257_0
  - ruamel.yaml.clib=0.2.14=py312he06e257_0
  - setuptools=80.9.0=pyhff2d567_0
  - simdjson=4.2.2=h49e36cd_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=h2c6b04d_3
  - tornado=6.5.4=py312he06e257_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - truststore=0.10.3=pyhe01879c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - wcwidth=0.5.3=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - yaml-cpp=0.8.0=he0c23c2_0
  - zeromq=4.3.5=h5bddc39_9
  - zstandard=0.25.0=py312he5662c2_1
  - zstd=1.5.7=h534d264_6

prefix: "C:\\Users\\braec\\miniforge3"
